In [1]:
# Import basic libraries
import pandas as pd
import numpy as np
import altair as alt

In [2]:
## librerías
#!pip install GetOldTweets3 #<- installa la librería

The system cannot find the file specified.

In [2]:
import GetOldTweets3 as got

In [4]:
# Partámetros para consulta
tweetCriteria = got.manager.TweetCriteria().setUsername("JustinTrudeau")\
                                           .setTopTweets(True)\
                                           .setMaxTweets(10)

In [5]:
# esto se almacena en un objeto
tweetCriteria

In [14]:

# # Al realizar la consulta arroja error
got.manager.tweetManager.getTweets(tweetCriteria)
#tweet = got.manager.TweetManager.getTweets(tweetCriteria)
# tweet = got.manager.TweetManager.getTweets(tweetCriteria)[0]
#tweet[0]

AttributeError: module 'GetOldTweets3.manager' has no attribute 'tweetManager'

In [3]:
# librerías
import snscrape.modules.twitter as sntwitter

In [17]:

# parametros
maxTweets = 2_000
date_initial = "2020-01-01"
date_final = "2022-10-31"

# twitter's accounts
cuentas=['JustinTrudeau', 'JoeBiden', 'lopezobrador_']

In [18]:
%%time
# Parámetros

# Creating list to append tweet data to
tweets_list = []

# Using TwitterSearchScraper to scrape data and append tweets to list
print("\n--- START: TwitterSearchScraper por cuenta de Twitter ---\n")
for a in cuentas:
    for i,tweet in enumerate(sntwitter.TwitterSearchScraper('"covid" since:'+date_initial+' until:'+date_final+' from:'+a).get_items()):
        if i>maxTweets-1:
            break
        tweets_list.append([tweet.user.username, tweet.date, tweet.id, tweet.content, tweet.url, tweet.lang,
                    tweet.hashtags, tweet.likeCount, tweet.replyCount, tweet.retweetCount, tweet.quoteCount])
        # Otra info que puede sernos útil: tweet.media,  tweet.url
    print("Se identificaron {0} tweets de la cuenta {1} con los parametros dados.".format(i, a))
print("\n--- END: TwitterSearchScraper ---\n\nTIMING")

--- START: TwitterSearchScraper por cuenta de Twitter ---

Se identificaron 1231 tweets de la cuenta JustinTrudeau con los parametros dados.
Se identificaron 255 tweets de la cuenta JoeBiden con los parametros dados.
Se identificaron 2 tweets de la cuenta lopezobrador_ con los parametros dados.

--- END: TwitterSearchScraper ---

TIMING
Wall time: 38.4 s

In [13]:
# Pandas dataframe con tweets de los tres presidentes relacionados con el Covid-19
column_names = ("username","date","id","content","url","language","hashtags",
                "likes_count","reply_count","retweet_count","quote_count")
df = pd.DataFrame(tweets_list, columns=column_names)
#df

NameError: name 'tweets_list' is not defined

In [20]:
# ejemplo de tweet
df['content'][0]

'And to Premier @JJHorgan: Thank you for your service to British Columbians and to all Canadians – particularly your leadership on reconciliation with Indigenous Peoples, and helping people during the COVID-19 pandemic. I’m wishing you the very best. https://t.co/X81iiqnqaW'

In [21]:
# Número de comentarios por presidente/primer ministro
print("\nTweets de presidente o primer ministro relacionados con el Covid-19, de enero 2020 a octubre 2022:\n")
pd.DataFrame(df['username'].value_counts()).reset_index().rename(columns={'index':'President', 'username':"tweets"})

Tweets de presidente o primer ministro relacionados con el Covid-19, de enero 2020 a octubre 2022:

       President  tweets
0  JustinTrudeau    1232
1       JoeBiden     256
2  lopezobrador_       3

In [22]:
%%time

# Parámetros
tweets_list_ine = []
maxTweets_ine = 100_000
date_initial = "2022-01-01"

# Get tweets
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('#INENoSeToca').get_items()): # se puede añadir esto --> since:'+date_initial
        if i>maxTweets_ine-1:
            break
        tweets_list_ine.append([tweet.user.username, tweet.date, tweet.id, tweet.content, tweet.url, tweet.lang,
                    tweet.hashtags, tweet.likeCount, tweet.replyCount, tweet.retweetCount, tweet.quoteCount])
        # Otra info que puede sernos útil: tweet.media,  tweet.url

Wall time: 9min 52s

In [23]:
# Pandas dataframe con tweets que mencionen el hashtag #INENoSeToca
df_ine = pd.DataFrame(tweets_list_ine, columns=column_names)
df_ine['date'] = df_ine['date'].dt.strftime('%Y-%m-%d')
df_ine

,username,date,id,content,url,language,hashtags,likes_count,reply_count,retweet_count,quote_count
0,AlexRan30405641,2022-11-23,1595534786843533328,@Arouet_V @INEMexico @avieu A ver si entiendo ...,https://twitter.com/AlexRan30405641/status/159...,es,[INENoSeToca],0,0,0,0
1,alexascacio,2022-11-23,1595534217290604566,@GPPRIDiputados @caroviggiano @alitomorenoc @P...,https://twitter.com/alexascacio/status/1595534...,es,[INENoSeToca],0,0,0,0
2,alexascacio,2022-11-23,1595532282231676937,@GPPRIDiputados @caroviggiano @alitomorenoc @P...,https://twitter.com/alexascacio/status/1595532...,es,[INENoSeToca],0,1,0,0
3,obelich,2022-11-23,1595527577556250625,LES CAMBIO LA JUGADA! OBRADOR (@lopezobrador_)...,https://twitter.com/obelich/status/15955275775...,es,"[AMLO, Politica, Mexico, INE, INENoSeToca, URG...",0,0,0,0
4,BrujaDeEstrada,2022-11-23,1595519990513692672,"#Sección36 del #SNTE , que corresponde al #Edo...",https://twitter.com/BrujaDeEstrada/status/1595...,es,"[Sección36, SNTE, Edomex, INENoSeToca]",1,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...
17026,EnriqueBedolla,2019-11-10,1193411453878845441,#INENoSeToca \n\n#INEUltimoBastion https://t.c...,https://twitter.com/EnriqueBedolla/status/1193...,qht,"[INENoSeToca, INEUltimoBastion]",0,0,1,0
17027,superharta99,2019-11-10,1193388698269896705,#INENoSeToca https://t.co/DNRHXgwJhG,https://twitter.com/superharta99/status/119338...,qme,[INENoSeToca],1,0,2,0
17028,superharta99,2019-11-10,1193388629483229184,#INENoSeToca,https://twitter.com/superharta99/status/119338...,qht,[INENoSeToca],0,0,1,0
17029,EnriqueBedolla,2019-11-10,1193387134922543109,#INENoSeToca https://t.co/T8mjiEEFXO,https://twitter.com/EnriqueBedolla/status/1193...,qht,[INENoSeToca],1,0,4,0
17030,EnriqueBedolla,2019-11-10,1193381402579853312,"Mexicanos, tenemos que salir a la calle y prot...",https://twitter.com/EnriqueBedolla/status/1193...,es,[INENoSeToca],1,0,2,0

In [24]:
# ejemplo de tweet
df_ine['content'][1]

'@GPPRIDiputados @caroviggiano @alitomorenoc @PRI_Nacional @INEMexico @TEPJF_informa @SantiagoCreelM @armentapuebla_ @SCJN @Mx_Diputados @senadomexicano @MiguelMery @GobDeCoahuila @PJCoah @Veronica_mtz @aguadiana @CJF_Mx @rubenmoreiravdz @jorgegarralda @chema_fraustro #INENoSeToca nunca a servido, décadas con Robos de Propiedades y ningún político las ERRADICA @MeyerFalcon @mrikelme @galaz_eva @CIJ_ICJ @manolojim @TheWJP @lopezobrador_ @Silvia_GarzaG @jaimebuenoz @PRICoahuila @gpeoyervides @rigofuentes @DiarioCoahuila @AmistadMex @MonikaZert https://t.co/xiKpmnKtN0'

In [25]:
source = pd.DataFrame(df_ine['date'].value_counts()).reset_index().rename(columns={'index':'fecha', 'date':"tweets"})
source.head()

        fecha  tweets
0  2022-11-13    6146
1  2022-11-14    2788
2  2022-11-09     770
3  2022-11-11     743
4  2022-11-12     735

In [26]:
alt.Chart(source[source['fecha'] >= "2022-01-01"]).mark_area(color="pink").encode(
    alt.X("fecha:T", title="2022"),
    alt.Y("tweets:Q", title="Número de Tweets", scale=alt.Scale(type="log")),
    tooltip=["fecha:T","tweets"]
).properties(
    title="Volumen de tweets con hashtag #INENoSeToca durante 2022"
)

alt.Chart(...)

In [29]:
# parametros
maxTweets = 2_000
date_initial = "2022-10-25"
date_final = "2022-10-26"

# twitter's accounts
cuentas=['JustinTrudeau', 'JoeBiden', 'lopezobrador_']

In [30]:
%%time
# Parámetros

# Creating list to append tweet data to
tweets_list = []

# Using TwitterSearchScraper to scrape data and append tweets to list
print("\n--- START: TwitterSearchScraper por cuenta de Twitter ---\n")
#for a in cuentas:
    for i,tweet in enumerate(sntwitter.TwitterSearchScraper('"covid" since:'+date_initial+' until:'+date_final).get_items()):
        if i>maxTweets-1:
            break
        tweets_list.append([tweet.user.username, tweet.date, tweet.id, tweet.content, tweet.url, tweet.lang,
                    tweet.hashtags, tweet.likeCount, tweet.replyCount, tweet.retweetCount, tweet.quoteCount])
        # Otra info que puede sernos útil: tweet.media,  tweet.url
    print("Se identificaron {0} tweets de la cuenta {1} con los parametros dados.".format(i, a))
print("\n--- END: TwitterSearchScraper ---\n\nTIMING")

IndentationError: unexpected indent (<unknown>, line 9)

In [131]:
%%time
# Setting variables to be used below
maxTweets = 100_000
# Creating list to append tweet data to
tweets_list2 = []
# Using TwitterSearchScraper to scrape data and append tweets to list
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('BuenFin since:2016-01-01 until:2022-12-12').get_items()):
    if i>maxTweets:
        break
    tweets_list2.append([tweet.date,tweet.user.username,  tweet.id, tweet.content, tweet.url, tweet.lang,
                    tweet.hashtags, tweet.likeCount, tweet.replyCount, tweet.retweetCount, tweet.quoteCount])

Wall time: 41min 53s

In [133]:
column_names = ("date","username","id","content","url","language","hashtags",
                "likes_count","reply_count","retweet_count","quote_count")
df_raw = pd.DataFrame(tweets_list2, columns=column_names)

,date,username,id,content,url,language,hashtags,likes_count,reply_count,retweet_count,quote_count
0,2022-11-25 01:14:38+00:00,CienciaNewsIn,1595949045880885248,La tecnología: Aliada clave para el éxito del ...,https://twitter.com/CienciaNewsIn/status/15959...,es,None,0,0,0,0
1,2022-11-25 01:14:05+00:00,ShalynArroyo,1595948908051849217,@TheKylieKingdom @M4LASDECISIONES @keniaos Pob...,https://twitter.com/ShalynArroyo/status/159594...,es,None,0,0,0,0
2,2022-11-25 01:13:46+00:00,TermCoyoacan,1595948827827179520,🗣📣 #cartelera #cursos #AcademiaONJMX #BlackFri...,https://twitter.com/TermCoyoacan/status/159594...,es,"[cartelera, cursos, AcademiaONJMX, BlackFriday...",0,0,0,0
3,2022-11-25 01:09:54+00:00,B0nnie_mp3,1595947852999831552,La moto que espero comprar en el buen fin 😻😻 ...,https://twitter.com/B0nnie_mp3/status/15959478...,es,None,0,0,0,0
4,2022-11-25 01:06:17+00:00,El_Neri_,1595946943217537031,Oye @Profeco ¿cómo se procede contra @liverpoo...,https://twitter.com/El_Neri_/status/1595946943...,es,None,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
99996,2022-09-24 00:18:04+00:00,Pepe_Lozada19,1573466761541844997,En el semáforo del X24 de Circuito Presidentes...,https://twitter.com/Pepe_Lozada19/status/15734...,es,None,3,0,0,0
99997,2022-09-24 00:17:50+00:00,EXOBubbleL,1573466705254285321,[220924] [#SEHUN] 💬🐣\n\n“Que tengas un buen fi...,https://twitter.com/EXOBubbleL/status/15734667...,es,[SEHUN],209,0,46,10
99998,2022-09-24 00:17:27+00:00,anagtzfuego,1573466607833075712,@Halcon_Negro_JR Desde el martes en la noche c...,https://twitter.com/anagtzfuego/status/1573466...,es,None,1,1,0,0
99999,2022-09-24 00:16:31+00:00,fraancogarciaa,1573466374315311110,Que tengan un buen fin de semana amigxs,https://twitter.com/fraancogarciaa/status/1573...,es,None,2,1,0,0
100000,2022-09-24 00:16:17+00:00,DoKyungLoey,1573466316014485507,"[240922] Mensaje de Sehun en la burbuja🐣\n\n""q...",https://twitter.com/DoKyungLoey/status/1573466...,es,None,194,0,39,2

In [134]:
df_raw['date'] = df_raw['date'].dt.strftime('%Y-%m-%d')
df_raw

,date,username,id,content,url,language,hashtags,likes_count,reply_count,retweet_count,quote_count
0,2022-11-25,CienciaNewsIn,1595949045880885248,La tecnología: Aliada clave para el éxito del ...,https://twitter.com/CienciaNewsIn/status/15959...,es,None,0,0,0,0
1,2022-11-25,ShalynArroyo,1595948908051849217,@TheKylieKingdom @M4LASDECISIONES @keniaos Pob...,https://twitter.com/ShalynArroyo/status/159594...,es,None,0,0,0,0
2,2022-11-25,TermCoyoacan,1595948827827179520,🗣📣 #cartelera #cursos #AcademiaONJMX #BlackFri...,https://twitter.com/TermCoyoacan/status/159594...,es,"[cartelera, cursos, AcademiaONJMX, BlackFriday...",0,0,0,0
3,2022-11-25,B0nnie_mp3,1595947852999831552,La moto que espero comprar en el buen fin 😻😻 ...,https://twitter.com/B0nnie_mp3/status/15959478...,es,None,0,0,0,0
4,2022-11-25,El_Neri_,1595946943217537031,Oye @Profeco ¿cómo se procede contra @liverpoo...,https://twitter.com/El_Neri_/status/1595946943...,es,None,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
99996,2022-09-24,Pepe_Lozada19,1573466761541844997,En el semáforo del X24 de Circuito Presidentes...,https://twitter.com/Pepe_Lozada19/status/15734...,es,None,3,0,0,0
99997,2022-09-24,EXOBubbleL,1573466705254285321,[220924] [#SEHUN] 💬🐣\n\n“Que tengas un buen fi...,https://twitter.com/EXOBubbleL/status/15734667...,es,[SEHUN],209,0,46,10
99998,2022-09-24,anagtzfuego,1573466607833075712,@Halcon_Negro_JR Desde el martes en la noche c...,https://twitter.com/anagtzfuego/status/1573466...,es,None,1,1,0,0
99999,2022-09-24,fraancogarciaa,1573466374315311110,Que tengan un buen fin de semana amigxs,https://twitter.com/fraancogarciaa/status/1573...,es,None,2,1,0,0
100000,2022-09-24,DoKyungLoey,1573466316014485507,"[240922] Mensaje de Sehun en la burbuja🐣\n\n""q...",https://twitter.com/DoKyungLoey/status/1573466...,es,None,194,0,39,2

In [135]:
from pathlib import Path  
filepath = Path('Documents/out_BuenFin.csv')  
filepath.parent.mkdir(parents=True, exist_ok=True)  
df_raw.to_csv(filepath)

In [137]:
df_raw2 = pd.read_csv('Documents/out_BuenFin.csv')

In [138]:
df_bf = df_raw2

In [139]:
df_bf.columns

Index(['Unnamed: 0', 'date', 'username', 'id', 'content', 'url', 'language',
       'hashtags', 'likes_count', 'reply_count', 'retweet_count',
       'quote_count'],
      dtype='object')

In [140]:
df_bf.drop(['Unnamed: 0'], axis=1)

,date,username,id,content,url,language,hashtags,likes_count,reply_count,retweet_count,quote_count
0,2022-11-25,CienciaNewsIn,1595949045880885248,La tecnología: Aliada clave para el éxito del ...,https://twitter.com/CienciaNewsIn/status/15959...,es,NaN,0,0,0,0
1,2022-11-25,ShalynArroyo,1595948908051849217,@TheKylieKingdom @M4LASDECISIONES @keniaos Pob...,https://twitter.com/ShalynArroyo/status/159594...,es,NaN,0,0,0,0
2,2022-11-25,TermCoyoacan,1595948827827179520,🗣📣 #cartelera #cursos #AcademiaONJMX #BlackFri...,https://twitter.com/TermCoyoacan/status/159594...,es,"['cartelera', 'cursos', 'AcademiaONJMX', 'Blac...",0,0,0,0
3,2022-11-25,B0nnie_mp3,1595947852999831552,La moto que espero comprar en el buen fin 😻😻 ...,https://twitter.com/B0nnie_mp3/status/15959478...,es,NaN,0,0,0,0
4,2022-11-25,El_Neri_,1595946943217537031,Oye @Profeco ¿cómo se procede contra @liverpoo...,https://twitter.com/El_Neri_/status/1595946943...,es,NaN,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
99996,2022-09-24,Pepe_Lozada19,1573466761541844997,En el semáforo del X24 de Circuito Presidentes...,https://twitter.com/Pepe_Lozada19/status/15734...,es,NaN,3,0,0,0
99997,2022-09-24,EXOBubbleL,1573466705254285321,[220924] [#SEHUN] 💬🐣\n\n“Que tengas un buen fi...,https://twitter.com/EXOBubbleL/status/15734667...,es,['SEHUN'],209,0,46,10
99998,2022-09-24,anagtzfuego,1573466607833075712,@Halcon_Negro_JR Desde el martes en la noche c...,https://twitter.com/anagtzfuego/status/1573466...,es,NaN,1,1,0,0
99999,2022-09-24,fraancogarciaa,1573466374315311110,Que tengan un buen fin de semana amigxs,https://twitter.com/fraancogarciaa/status/1573...,es,NaN,2,1,0,0
100000,2022-09-24,DoKyungLoey,1573466316014485507,"[240922] Mensaje de Sehun en la burbuja🐣\n\n""q...",https://twitter.com/DoKyungLoey/status/1573466...,es,NaN,194,0,39,2

In [141]:
#df_bf['date'] = df_bf['date'].strftime('%Y-%m-%d')
df_bf['date'] = pd.to_datetime(df_bf['date'], infer_datetime_format=True)

In [142]:
df_bf

,Unnamed: 0,date,username,id,content,url,language,hashtags,likes_count,reply_count,retweet_count,quote_count
0,0,2022-11-25,CienciaNewsIn,1595949045880885248,La tecnología: Aliada clave para el éxito del ...,https://twitter.com/CienciaNewsIn/status/15959...,es,NaN,0,0,0,0
1,1,2022-11-25,ShalynArroyo,1595948908051849217,@TheKylieKingdom @M4LASDECISIONES @keniaos Pob...,https://twitter.com/ShalynArroyo/status/159594...,es,NaN,0,0,0,0
2,2,2022-11-25,TermCoyoacan,1595948827827179520,🗣📣 #cartelera #cursos #AcademiaONJMX #BlackFri...,https://twitter.com/TermCoyoacan/status/159594...,es,"['cartelera', 'cursos', 'AcademiaONJMX', 'Blac...",0,0,0,0
3,3,2022-11-25,B0nnie_mp3,1595947852999831552,La moto que espero comprar en el buen fin 😻😻 ...,https://twitter.com/B0nnie_mp3/status/15959478...,es,NaN,0,0,0,0
4,4,2022-11-25,El_Neri_,1595946943217537031,Oye @Profeco ¿cómo se procede contra @liverpoo...,https://twitter.com/El_Neri_/status/1595946943...,es,NaN,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
99996,99996,2022-09-24,Pepe_Lozada19,1573466761541844997,En el semáforo del X24 de Circuito Presidentes...,https://twitter.com/Pepe_Lozada19/status/15734...,es,NaN,3,0,0,0
99997,99997,2022-09-24,EXOBubbleL,1573466705254285321,[220924] [#SEHUN] 💬🐣\n\n“Que tengas un buen fi...,https://twitter.com/EXOBubbleL/status/15734667...,es,['SEHUN'],209,0,46,10
99998,99998,2022-09-24,anagtzfuego,1573466607833075712,@Halcon_Negro_JR Desde el martes en la noche c...,https://twitter.com/anagtzfuego/status/1573466...,es,NaN,1,1,0,0
99999,99999,2022-09-24,fraancogarciaa,1573466374315311110,Que tengan un buen fin de semana amigxs,https://twitter.com/fraancogarciaa/status/1573...,es,NaN,2,1,0,0
100000,100000,2022-09-24,DoKyungLoey,1573466316014485507,"[240922] Mensaje de Sehun en la burbuja🐣\n\n""q...",https://twitter.com/DoKyungLoey/status/1573466...,es,NaN,194,0,39,2

In [143]:
df_bf.dtypes

Unnamed: 0                int64
date             datetime64[ns]
username                 object
id                        int64
content                  object
url                      object
language                 object
hashtags                 object
likes_count               int64
reply_count               int64
retweet_count             int64
quote_count               int64
dtype: object

In [144]:
dates = pd.DataFrame(df_bf['date'].value_counts()).reset_index().rename(columns={'index':'fecha', 'date':"tweets"})
dates.head()

       fecha  tweets
0 2022-11-18   11508
1 2022-11-19    8970
2 2022-11-21    4955
3 2022-11-20    4824
4 2022-11-17    4306

In [145]:
df_bf.nunique()

Unnamed: 0       100001
date                 63
username          57865
id               100001
content           97244
url              100001
language             33
hashtags          11650
likes_count         505
reply_count         128
retweet_count       198
quote_count          54
dtype: int64

In [146]:
buffer = pd.DataFrame(df_bf['language']).reset_index().rename(columns={'index':'fecha', 'date':"tweets"})

In [147]:
buffer

         fecha language
0            0       es
1            1       es
2            2       es
3            3       es
4            4       es
...        ...      ...
99996    99996       es
99997    99997       es
99998    99998       es
99999    99999       es
100000  100000       es

[100001 rows x 2 columns]

In [148]:
buffer = buffer.drop(['fecha'],axis=1)

In [149]:
buffer

       language
0            es
1            es
2            es
3            es
4            es
...         ...
99996        es
99997        es
99998        es
99999        es
100000       es

[100001 rows x 1 columns]

In [150]:
buffer = buffer.drop_duplicates(subset=['language'])

In [84]:
buffer

       language
0            es
53           en
161         qht
598          eu
700          ca
782         qam
849         zxx
867          in
907         qme
936          it
1985         de
2051         ja
2523        und
4126         ro
5564         cy
5709         tl
5726         pl
6011         ht
6280         pt
8114         da
10912        fr
12323        fi
12932        nl
13294        hi
15433        tr
19606        sv
21824        ko
22375        lt
22458        no
27087        cs
42224        et
58263        zh
59977        hu
102092       sl
113719       th
245114       ru
261577       bg

In [153]:
buffer = pd.DataFrame(df_bf['date']).reset_index().rename(columns={'date':"date"})

In [154]:
buffer = buffer.drop(['index'],axis = 1)

In [155]:
buffer

             date
0      2022-11-25
1      2022-11-25
2      2022-11-25
3      2022-11-25
4      2022-11-25
...           ...
99996  2022-09-24
99997  2022-09-24
99998  2022-09-24
99999  2022-09-24
100000 2022-09-24

[100001 rows x 1 columns]

In [156]:
buffer = buffer.drop_duplicates(subset=['date'])

In [158]:
buffer.head(100)

            date
0     2022-11-25
72    2022-11-24
1051  2022-11-23
2551  2022-11-22
5748  2022-11-21
...          ...
96907 2022-09-28
97010 2022-09-27
97166 2022-09-26
97813 2022-09-25
98304 2022-09-24

[63 rows x 1 columns]

In [161]:
year = buffer['date'][0].strftime("%Y")

In [162]:
year

'2022'